name: Code Analysis

on:
  pull_request:
  push:
    branches: [main, develop]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  run:
    name: Run
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-code-analysis.yml@self-hosted
    permissions: write-all
    with:
      solution-name: '<<el nombre del archivo de tu solucion, por ejemplo: Test.slnx o Test.sln>>'
